# Generated by Django 5.2.6 on 2025-09-16 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('customer', 'Customer'), ('driver', 'Driver'), ('agent', 'Agent')], max_length=8),
        ),
    ]
